# Generated by Django 6.1.1 on 2026-09-21 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='complaints/')),
                ('ai_verification_status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('UNCERTAIN', 'Uncertain'), ('PENDING', 'Pending Verification')], default='PENDING', max_length=20)),
                ('ai_verification_reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PENDING', 'Pending'), ('RESOLVED', 'Resolved')], default='NEW', max_length=20)),
                ('resolution_description', models.TextField(blank=True, null=True)),
                ('resolution_image', models.ImageField(blank=True, null=True, upload_to='resolutions/')),
                ('resolution_ai_status', models.CharField(blank=True, choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('UNCERTAIN', 'Uncertain'), ('PENDING', 'Pending Verification')], max_length=20, null=True)),
                ('resolution_ai_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
